gantt
    dateFormat  YY-MM-DD
    axisFormat w%W, %d.%m
    title       Дорожная карта развития SEAF в прикладном слое 2024Q1
%%    excludes    weekends
%%    axisFormat %m-%d
%%    Работы над SEAF со стороны фокусной группы и Команды Продукта в слое ПА в 2024Q1 : 24-01-11, 24-03-31
    section Прикладная архитектура
    Доработка Slice Pack (функций преобразования для КА ДЗО)      :  active,     24-01-12, 30d
    Сбор метаданных о ПА из GitLab                                :  active,     24-01-28, 20d
    Управление портфелем приложений                               :  active,     24-01-28, 20d
    Проверки требований стандартов к ПА SEAF-DZO                  :  active,     24-01-28, 20d
    Проверки требований КБ к ПА SEAF-DZO                          :  active,     24-01-28, 20d
    Проверки форматно-логического контроля SEAF и SEAF-DZO        :  active,     24-02-28, 20d
    Расширение примера описания архитектуры (Онлайнмаркет)        :  active,     24-02-28, 20d
%% Все работы подлежат уточнению и приоритизации с фокусной группой SEAF-DZO

