gantt
    dateFormat  YY-MM-DD
    axisFormat w%W, %d.%m
    title       Дорожная карта развития технического слоя SEAF 2024Q1
    section Техническая архитектура
        Реверс описания архитектуры из LinkerD                        :       24-03-17, 30d
        Автоматизация формирования схемы Р41                          :       24-03-17, 30d
        Проверки требований стандартов к ТА SEAF                      :       24-01-17, 30d
        Проверки требований КБ к ТА SEAF                              :       24-02-17, 30d

