@startuml

top to bottom direction
set separator ..
hide empty description

!$url = "{{{url}}}"

{{#nodes}}
{{#path}}
!$path = "{{.}}" 
{{#body.bage}}sprite ${{bId}} {{{svg}}}{{/body.bage}}
state "{{#body.bage}}<${{bId}}> {{/body.bage}}{{body.title}}" as $path {
     $path: <b>id:{{id}}</b>
}
{{/path}}
{{^path}}
{{#body.bage}}sprite ${{bId}} {{{svg}}}{{/body.bage}}
state "{{#body.bage}}<${{bId}}> {{/body.bage}}{{body.title}}" as {{id}} {
     {{id}}: <b>id:{{id}}</b>
}
{{/path}}

' {{#body.bage}}sprite ${{bId}} {{{svg}}}{{/body.bage}}
' state "{{#body.bage}}<${{bId}}> {{/body.bage}}{{body.title}}" as {{#path}}{{.}}{{/path}}{{^path}}{{id}}{{/path}} {
'      {{#path}}{{.}}{{/path}}{{^path}}{{id}}{{/path}}: <b>id:{{id}}</b>
' }

{{/nodes}}

{{#edges}}
{{source}} --> {{target}} {{#label}}: {{.}}{{/label}}
{{/edges}}
@enduml